[2023-08-03T06:37:05.467+0000] {processor.py:156} INFO - Started process (PID=33) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:37:05.468+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T06:37:05.469+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:37:05.469+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:37:05.485+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:37:05.481+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T06:37:05.487+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:37:05.605+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.143 seconds
[2023-08-03T06:37:36.034+0000] {processor.py:156} INFO - Started process (PID=91) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:37:36.035+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T06:37:36.036+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:37:36.036+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:37:36.044+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:37:36.042+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T06:37:36.045+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:37:36.067+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.037 seconds
[2023-08-03T06:38:06.674+0000] {processor.py:156} INFO - Started process (PID=149) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:38:06.676+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T06:38:06.677+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:38:06.677+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:38:06.683+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:38:06.682+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T06:38:06.684+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:38:06.703+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.036 seconds
[2023-08-03T06:38:37.241+0000] {processor.py:156} INFO - Started process (PID=207) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:38:37.242+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T06:38:37.244+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:38:37.244+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:38:37.250+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:38:37.248+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T06:38:37.250+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:38:37.273+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.038 seconds
[2023-08-03T06:39:07.493+0000] {processor.py:156} INFO - Started process (PID=265) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:39:07.495+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T06:39:07.496+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:39:07.496+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:39:07.506+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:39:07.502+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T06:39:07.507+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:39:07.534+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.045 seconds
[2023-08-03T06:40:53.259+0000] {processor.py:156} INFO - Started process (PID=32) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:40:53.262+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T06:40:53.265+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:40:53.265+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:40:53.280+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:40:53.270+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T06:40:53.281+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:40:53.344+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.095 seconds
[2023-08-03T06:41:23.939+0000] {processor.py:156} INFO - Started process (PID=90) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:41:23.941+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T06:41:23.942+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:41:23.941+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:41:23.948+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:41:23.946+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T06:41:23.948+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:41:23.971+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.037 seconds
[2023-08-03T06:41:54.524+0000] {processor.py:156} INFO - Started process (PID=148) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:41:54.525+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T06:41:54.527+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:41:54.527+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:41:54.534+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:41:54.532+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T06:41:54.535+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:41:54.559+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.039 seconds
[2023-08-03T06:42:25.332+0000] {processor.py:156} INFO - Started process (PID=206) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:42:25.333+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T06:42:25.334+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:42:25.334+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:42:25.341+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:42:25.339+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T06:42:25.342+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:42:25.368+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.040 seconds
[2023-08-03T06:42:55.923+0000] {processor.py:156} INFO - Started process (PID=264) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:42:55.924+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T06:42:55.925+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:42:55.925+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:42:55.930+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:42:55.929+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T06:42:55.931+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:42:55.953+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.034 seconds
[2023-08-03T06:43:26.645+0000] {processor.py:156} INFO - Started process (PID=322) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:43:26.650+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T06:43:26.651+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:43:26.651+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:43:26.666+0000] {logging_mixin.py:149} INFO - [2023-08-03T06:43:26.659+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T06:43:26.669+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T06:43:26.738+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.098 seconds
[2023-08-03T15:11:04.245+0000] {processor.py:157} INFO - Started process (PID=31) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:11:04.249+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:11:04.257+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:11:04.257+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:11:04.277+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:11:04.270+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:11:04.279+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:11:04.357+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.121 seconds
[2023-08-03T15:11:34.802+0000] {processor.py:157} INFO - Started process (PID=61) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:11:34.804+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:11:34.806+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:11:34.805+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:11:34.813+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:11:34.811+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:11:34.814+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:11:34.844+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.047 seconds
[2023-08-03T15:12:05.277+0000] {processor.py:157} INFO - Started process (PID=91) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:12:05.280+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:12:05.281+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:12:05.281+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:12:05.295+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:12:05.289+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:12:05.296+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:12:05.337+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.065 seconds
[2023-08-03T15:12:35.742+0000] {processor.py:157} INFO - Started process (PID=111) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:12:35.752+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:12:35.757+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:12:35.757+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:12:35.775+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:12:35.770+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:12:35.777+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:12:35.827+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.090 seconds
[2023-08-03T15:13:06.061+0000] {processor.py:157} INFO - Started process (PID=140) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:13:06.062+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:13:06.064+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:13:06.063+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:13:06.073+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:13:06.071+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:13:06.074+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:13:06.100+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.043 seconds
[2023-08-03T15:13:36.489+0000] {processor.py:157} INFO - Started process (PID=159) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:13:36.491+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:13:36.492+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:13:36.492+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:13:36.504+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:13:36.501+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:13:36.504+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:13:36.532+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.047 seconds
[2023-08-03T15:14:06.875+0000] {processor.py:157} INFO - Started process (PID=187) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:14:06.877+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:14:06.878+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:14:06.878+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:14:06.891+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:14:06.884+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:14:06.892+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:14:06.932+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.061 seconds
[2023-08-03T15:14:37.365+0000] {processor.py:157} INFO - Started process (PID=208) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:14:37.368+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:14:37.370+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:14:37.369+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:14:37.382+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:14:37.379+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:14:37.383+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:14:37.412+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.052 seconds
[2023-08-03T15:15:07.811+0000] {processor.py:157} INFO - Started process (PID=237) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:15:07.814+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:15:07.815+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:15:07.815+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:15:07.823+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:15:07.820+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:15:07.823+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:15:07.858+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.051 seconds
[2023-08-03T15:15:38.190+0000] {processor.py:157} INFO - Started process (PID=266) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:15:38.192+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:15:38.194+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:15:38.193+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:15:38.202+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:15:38.200+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:15:38.203+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:15:38.230+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.044 seconds
[2023-08-03T15:16:08.587+0000] {processor.py:157} INFO - Started process (PID=286) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:16:08.589+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:16:08.590+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:16:08.589+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:16:08.595+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:16:08.594+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:16:08.596+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:16:08.619+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.035 seconds
[2023-08-03T15:16:38.877+0000] {processor.py:157} INFO - Started process (PID=315) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:16:38.879+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:16:38.880+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:16:38.880+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:16:38.887+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:16:38.885+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:16:38.889+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:16:38.916+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.044 seconds
[2023-08-03T15:17:09.159+0000] {processor.py:157} INFO - Started process (PID=346) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:17:09.161+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:17:09.163+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:17:09.162+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:17:09.169+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:17:09.167+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:17:09.170+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:17:09.200+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.045 seconds
[2023-08-03T15:17:39.456+0000] {processor.py:157} INFO - Started process (PID=377) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:17:39.457+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:17:39.458+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:17:39.458+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:17:39.465+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:17:39.463+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:17:39.466+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:17:39.490+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.038 seconds
[2023-08-03T15:18:09.809+0000] {processor.py:157} INFO - Started process (PID=405) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:18:09.811+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:18:09.813+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:18:09.812+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:18:09.821+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:18:09.819+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:18:09.822+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:18:09.854+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.049 seconds
[2023-08-03T15:18:40.263+0000] {processor.py:157} INFO - Started process (PID=427) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:18:40.264+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:18:40.268+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:18:40.267+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:18:40.282+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:18:40.279+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:18:40.283+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:18:40.355+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.096 seconds
[2023-08-03T15:19:10.741+0000] {processor.py:157} INFO - Started process (PID=456) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:19:10.743+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:19:10.744+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:19:10.744+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:19:10.756+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:19:10.754+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:19:10.757+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:19:10.790+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.053 seconds
[2023-08-03T15:19:41.271+0000] {processor.py:157} INFO - Started process (PID=486) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:19:41.273+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:19:41.274+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:19:41.274+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:19:41.280+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:19:41.279+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:19:41.281+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:19:41.301+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.035 seconds
[2023-08-03T15:20:11.710+0000] {processor.py:157} INFO - Started process (PID=506) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:20:11.712+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:20:11.713+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:20:11.713+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:20:11.720+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:20:11.718+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:20:11.721+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:20:11.745+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.039 seconds
[2023-08-03T15:20:42.119+0000] {processor.py:157} INFO - Started process (PID=535) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:20:42.121+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:20:42.123+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:20:42.122+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:20:42.129+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:20:42.128+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:20:42.130+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:20:42.151+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.036 seconds
[2023-08-03T15:21:12.657+0000] {processor.py:157} INFO - Started process (PID=564) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:21:12.659+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:21:12.660+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:21:12.660+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:21:12.668+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:21:12.666+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:21:12.669+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:21:12.692+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.039 seconds
[2023-08-03T15:21:43.103+0000] {processor.py:157} INFO - Started process (PID=584) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:21:43.106+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:21:43.108+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:21:43.107+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:21:43.124+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:21:43.122+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:21:43.125+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:21:43.168+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.070 seconds
[2023-08-03T15:22:13.532+0000] {processor.py:157} INFO - Started process (PID=613) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:22:13.534+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:22:13.536+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:22:13.535+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:22:13.545+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:22:13.543+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:22:13.546+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:22:13.575+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.047 seconds
[2023-08-03T15:22:43.943+0000] {processor.py:157} INFO - Started process (PID=643) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:22:43.946+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:22:43.951+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:22:43.950+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:22:43.968+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:22:43.965+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:22:43.968+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:22:43.998+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.059 seconds
[2023-08-03T15:23:14.422+0000] {processor.py:157} INFO - Started process (PID=663) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:23:14.424+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:23:14.425+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:23:14.425+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:23:14.432+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:23:14.430+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:23:14.433+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:23:14.464+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.046 seconds
[2023-08-03T15:23:44.948+0000] {processor.py:157} INFO - Started process (PID=691) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:23:44.950+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:23:44.951+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:23:44.951+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:23:44.959+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:23:44.957+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:23:44.960+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:23:44.981+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.039 seconds
[2023-08-03T15:24:15.372+0000] {processor.py:157} INFO - Started process (PID=711) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:24:15.375+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:24:15.377+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:24:15.376+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:24:15.389+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:24:15.387+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:24:15.389+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:24:15.430+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.067 seconds
[2023-08-03T15:24:45.810+0000] {processor.py:157} INFO - Started process (PID=741) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:24:45.812+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:24:45.813+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:24:45.813+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:24:45.820+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:24:45.818+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:24:45.820+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:24:45.842+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.036 seconds
[2023-08-03T15:25:16.235+0000] {processor.py:157} INFO - Started process (PID=770) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:25:16.237+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:25:16.239+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:25:16.238+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:25:16.249+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:25:16.247+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:25:16.250+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:25:16.282+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.058 seconds
[2023-08-03T15:25:46.719+0000] {processor.py:157} INFO - Started process (PID=790) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:25:46.721+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:25:46.723+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:25:46.722+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:25:46.732+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:25:46.730+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:25:46.733+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:25:46.761+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.048 seconds
[2023-08-03T15:26:17.224+0000] {processor.py:157} INFO - Started process (PID=820) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:26:17.226+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:26:17.228+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:26:17.227+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:26:17.239+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:26:17.236+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:26:17.240+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:26:17.269+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.049 seconds
[2023-08-03T15:26:47.620+0000] {processor.py:157} INFO - Started process (PID=849) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:26:47.622+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:26:47.624+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:26:47.623+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:26:47.642+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:26:47.640+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:26:47.643+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:26:47.675+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.061 seconds
[2023-08-03T15:27:18.079+0000] {processor.py:157} INFO - Started process (PID=869) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:27:18.083+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:27:18.085+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:27:18.084+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:27:18.096+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:27:18.094+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:27:18.097+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:27:18.122+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.055 seconds
[2023-08-03T15:27:48.632+0000] {processor.py:157} INFO - Started process (PID=898) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:27:48.634+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:27:48.637+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:27:48.636+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:27:48.648+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:27:48.646+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:27:48.649+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:27:48.671+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.048 seconds
[2023-08-03T15:28:19.014+0000] {processor.py:157} INFO - Started process (PID=919) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:28:19.016+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:28:19.018+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:28:19.018+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:28:19.028+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:28:19.026+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:28:19.029+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:28:19.055+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.047 seconds
[2023-08-03T15:28:49.618+0000] {processor.py:157} INFO - Started process (PID=948) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:28:49.621+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:28:49.623+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:28:49.622+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:28:49.635+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:28:49.631+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:28:49.636+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:28:49.679+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.070 seconds
[2023-08-03T15:29:20.014+0000] {processor.py:157} INFO - Started process (PID=977) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:29:20.016+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:29:20.018+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:29:20.017+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:29:20.035+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:29:20.025+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:29:20.037+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:29:20.059+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.050 seconds
[2023-08-03T15:29:50.577+0000] {processor.py:157} INFO - Started process (PID=997) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:29:50.579+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:29:50.581+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:29:50.581+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:29:50.593+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:29:50.589+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:29:50.594+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:29:50.630+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.068 seconds
[2023-08-03T15:30:21.071+0000] {processor.py:157} INFO - Started process (PID=1026) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:30:21.073+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:30:21.075+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:30:21.075+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:30:21.084+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:30:21.081+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:30:21.085+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:30:21.129+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.063 seconds
[2023-08-03T15:30:51.526+0000] {processor.py:157} INFO - Started process (PID=1047) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:30:51.528+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:30:51.530+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:30:51.529+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:30:51.537+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:30:51.535+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:30:51.538+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:30:51.565+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.044 seconds
[2023-08-03T15:31:21.916+0000] {processor.py:157} INFO - Started process (PID=1077) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:31:21.919+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:31:21.921+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:31:21.920+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:31:21.931+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:31:21.929+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:31:21.932+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:31:21.958+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.051 seconds
[2023-08-03T15:31:52.268+0000] {processor.py:157} INFO - Started process (PID=1107) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:31:52.269+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:31:52.271+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:31:52.270+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:31:52.279+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:31:52.276+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:31:52.280+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:31:52.307+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.044 seconds
[2023-08-03T15:32:22.721+0000] {processor.py:157} INFO - Started process (PID=1126) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:32:22.723+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:32:22.725+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:32:22.725+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:32:22.735+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:32:22.732+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:32:22.736+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:32:22.758+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.043 seconds
[2023-08-03T15:32:53.163+0000] {processor.py:157} INFO - Started process (PID=1154) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:32:53.166+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:32:53.168+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:32:53.167+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:32:53.178+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:32:53.176+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:32:53.180+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:32:53.225+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.086 seconds
[2023-08-03T15:33:23.661+0000] {processor.py:157} INFO - Started process (PID=1183) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:33:23.662+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:33:23.663+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:33:23.663+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:33:23.671+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:33:23.669+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:33:23.671+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:33:23.695+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.040 seconds
[2023-08-03T15:33:54.165+0000] {processor.py:157} INFO - Started process (PID=1203) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:33:54.168+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:33:54.171+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:33:54.170+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:33:54.185+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:33:54.182+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:33:54.186+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:33:54.224+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.069 seconds
[2023-08-03T15:34:24.636+0000] {processor.py:157} INFO - Started process (PID=1233) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:34:24.638+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:34:24.640+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:34:24.639+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:34:24.648+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:34:24.646+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:34:24.649+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:34:24.671+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.041 seconds
[2023-08-03T15:34:55.062+0000] {processor.py:157} INFO - Started process (PID=1260) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:34:55.064+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:34:55.065+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:34:55.065+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:34:55.072+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:34:55.071+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:34:55.073+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:34:55.099+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.042 seconds
[2023-08-03T15:35:26.162+0000] {processor.py:157} INFO - Started process (PID=1282) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:35:26.166+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:35:26.168+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:35:26.167+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:35:26.177+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:35:26.174+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:35:26.178+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:35:26.209+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.054 seconds
[2023-08-03T15:35:56.831+0000] {processor.py:157} INFO - Started process (PID=1312) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:35:56.833+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:35:56.836+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:35:56.835+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:35:56.848+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:35:56.845+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:35:56.848+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:35:56.871+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.050 seconds
[2023-08-03T15:36:27.300+0000] {processor.py:157} INFO - Started process (PID=1332) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:36:27.302+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:36:27.304+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:36:27.304+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:36:27.312+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:36:27.310+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:36:27.313+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:36:27.334+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.040 seconds
[2023-08-03T15:36:58.148+0000] {processor.py:157} INFO - Started process (PID=1361) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:36:58.150+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:36:58.152+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:36:58.151+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:36:58.164+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:36:58.158+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:36:58.165+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:36:58.205+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.069 seconds
[2023-08-03T15:51:09.593+0000] {processor.py:157} INFO - Started process (PID=1374) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:51:09.596+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:51:09.598+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:51:09.597+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:51:09.615+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:51:09.613+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:51:09.620+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:51:09.680+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.098 seconds
[2023-08-03T15:51:40.208+0000] {processor.py:157} INFO - Started process (PID=1403) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:51:40.210+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T15:51:40.212+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:51:40.211+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:51:40.220+0000] {logging_mixin.py:150} INFO - [2023-08-03T15:51:40.218+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T15:51:40.221+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T15:51:40.249+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.045 seconds
[2023-08-03T16:07:22.291+0000] {processor.py:157} INFO - Started process (PID=1432) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:07:22.303+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:07:22.304+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:07:22.304+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:07:22.337+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:07:22.329+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:07:22.339+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:07:22.411+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.140 seconds
[2023-08-03T16:07:52.919+0000] {processor.py:157} INFO - Started process (PID=1453) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:07:52.920+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:07:52.921+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:07:52.921+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:07:52.929+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:07:52.927+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:07:52.930+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:07:52.953+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.037 seconds
[2023-08-03T16:23:59.328+0000] {processor.py:157} INFO - Started process (PID=1482) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:23:59.329+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:23:59.330+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:23:59.329+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:23:59.336+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:23:59.335+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:23:59.337+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:23:59.352+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.027 seconds
[2023-08-03T16:24:29.885+0000] {processor.py:157} INFO - Started process (PID=1502) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:24:29.887+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:24:29.888+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:24:29.887+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:24:29.896+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:24:29.893+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:24:29.897+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:24:29.922+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.041 seconds
[2023-08-03T16:25:00.289+0000] {processor.py:157} INFO - Started process (PID=1531) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:25:00.291+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:25:00.292+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:25:00.292+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:25:00.299+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:25:00.297+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:25:00.300+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:25:00.322+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.037 seconds
[2023-08-03T16:25:30.709+0000] {processor.py:157} INFO - Started process (PID=1560) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:25:30.711+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:25:30.712+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:25:30.712+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:25:30.718+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:25:30.717+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:25:30.719+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:25:30.738+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.034 seconds
[2023-08-03T16:26:01.202+0000] {processor.py:157} INFO - Started process (PID=1580) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:26:01.204+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:26:01.206+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:26:01.205+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:26:01.213+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:26:01.211+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:26:01.214+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:26:01.233+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.037 seconds
[2023-08-03T16:26:31.652+0000] {processor.py:157} INFO - Started process (PID=1610) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:26:31.654+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:26:31.655+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:26:31.655+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:26:31.663+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:26:31.661+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:26:31.664+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:26:31.684+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.037 seconds
[2023-08-03T16:27:02.118+0000] {processor.py:157} INFO - Started process (PID=1639) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:27:02.120+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:27:02.122+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:27:02.121+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:27:02.128+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:27:02.127+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:27:02.129+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:27:02.150+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.036 seconds
[2023-08-03T16:27:32.580+0000] {processor.py:157} INFO - Started process (PID=1669) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:27:32.581+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:27:32.583+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:27:32.582+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:27:32.589+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:27:32.587+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:27:32.590+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:27:32.611+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.035 seconds
[2023-08-03T16:28:03.136+0000] {processor.py:157} INFO - Started process (PID=1689) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:28:03.138+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:28:03.139+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:28:03.139+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:28:03.146+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:28:03.144+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:28:03.146+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:28:03.167+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.035 seconds
[2023-08-03T16:28:33.602+0000] {processor.py:157} INFO - Started process (PID=1718) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:28:33.603+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:28:33.604+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:28:33.604+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:28:33.610+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:28:33.609+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:28:33.611+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:28:33.628+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.030 seconds
[2023-08-03T16:29:04.142+0000] {processor.py:157} INFO - Started process (PID=1746) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:29:04.144+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:29:04.146+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:29:04.146+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:29:04.154+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:29:04.152+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:29:04.157+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:29:04.176+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.038 seconds
[2023-08-03T16:29:34.582+0000] {processor.py:157} INFO - Started process (PID=1766) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:29:34.584+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:29:34.585+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:29:34.585+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:29:34.590+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:29:34.589+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:29:34.591+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:29:34.609+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.030 seconds
[2023-08-03T16:30:05.044+0000] {processor.py:157} INFO - Started process (PID=1795) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:30:05.045+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:30:05.047+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:30:05.046+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:30:05.053+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:30:05.051+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:30:05.054+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:30:05.075+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.035 seconds
[2023-08-03T16:30:35.440+0000] {processor.py:157} INFO - Started process (PID=1823) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:30:35.442+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:30:35.443+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:30:35.443+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:30:35.450+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:30:35.448+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:30:35.451+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:30:35.472+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.035 seconds
[2023-08-03T16:31:05.974+0000] {processor.py:157} INFO - Started process (PID=1843) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:31:05.976+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:31:05.978+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:31:05.977+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:31:05.984+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:31:05.983+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:31:05.985+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:31:06.005+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.037 seconds
[2023-08-03T16:31:36.403+0000] {processor.py:157} INFO - Started process (PID=1872) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:31:36.404+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:31:36.406+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:31:36.405+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:31:36.411+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:31:36.410+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:31:36.412+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:31:36.429+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.030 seconds
[2023-08-03T16:32:06.897+0000] {processor.py:157} INFO - Started process (PID=1899) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:32:06.898+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:32:06.900+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:32:06.899+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:32:06.909+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:32:06.907+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:32:06.910+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:32:06.932+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.040 seconds
[2023-08-03T16:32:37.392+0000] {processor.py:157} INFO - Started process (PID=1919) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:32:37.394+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:32:37.395+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:32:37.395+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:32:37.401+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:32:37.399+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:32:37.402+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:32:37.424+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.036 seconds
[2023-08-03T16:33:07.786+0000] {processor.py:157} INFO - Started process (PID=1947) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:33:07.788+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:33:07.789+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:33:07.789+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:33:07.797+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:33:07.795+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:33:07.797+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:33:07.822+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.040 seconds
[2023-08-03T16:33:38.214+0000] {processor.py:157} INFO - Started process (PID=1976) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:33:38.215+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:33:38.217+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:33:38.216+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:33:38.222+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:33:38.221+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:33:38.224+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:33:38.241+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.031 seconds
[2023-08-03T16:34:08.734+0000] {processor.py:157} INFO - Started process (PID=2005) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:34:08.735+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:34:08.736+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:34:08.735+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:34:08.741+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:34:08.740+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:34:08.742+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:34:08.760+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.029 seconds
[2023-08-03T16:34:39.232+0000] {processor.py:157} INFO - Started process (PID=2025) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:34:39.234+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:34:39.236+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:34:39.235+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:34:39.243+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:34:39.242+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:34:39.244+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:34:39.264+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.036 seconds
[2023-08-03T16:35:09.693+0000] {processor.py:157} INFO - Started process (PID=2056) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:35:09.694+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:35:09.695+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:35:09.695+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:35:09.702+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:35:09.700+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:35:09.703+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:35:09.730+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.040 seconds
[2023-08-03T16:35:40.176+0000] {processor.py:157} INFO - Started process (PID=2085) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:35:40.177+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:35:40.178+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:35:40.178+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:35:40.183+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:35:40.181+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:35:40.183+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:35:40.201+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.028 seconds
[2023-08-03T16:36:10.664+0000] {processor.py:157} INFO - Started process (PID=2105) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:36:10.665+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:36:10.667+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:36:10.666+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:36:10.673+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:36:10.671+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:36:10.673+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:36:10.693+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.034 seconds
[2023-08-03T16:36:41.164+0000] {processor.py:157} INFO - Started process (PID=2134) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:36:41.166+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:36:41.169+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:36:41.169+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:36:41.177+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:36:41.176+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:36:41.178+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:36:41.200+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.042 seconds
[2023-08-03T16:37:11.533+0000] {processor.py:157} INFO - Started process (PID=2163) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:37:11.534+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:37:11.536+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:37:11.536+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:37:11.546+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:37:11.545+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:37:11.547+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:37:11.564+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.034 seconds
[2023-08-03T16:37:41.930+0000] {processor.py:157} INFO - Started process (PID=2183) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:37:41.932+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:37:41.934+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:37:41.933+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:37:41.939+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:37:41.938+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:37:41.940+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:37:41.955+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.029 seconds
[2023-08-03T16:38:12.322+0000] {processor.py:157} INFO - Started process (PID=2210) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:38:12.323+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:38:12.324+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:38:12.324+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:38:12.329+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:38:12.328+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:38:12.330+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:38:12.348+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.029 seconds
[2023-08-03T16:38:42.720+0000] {processor.py:157} INFO - Started process (PID=2239) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:38:42.721+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:38:42.722+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:38:42.722+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:38:42.728+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:38:42.726+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:38:42.728+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:38:42.749+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.032 seconds
[2023-08-03T16:39:13.212+0000] {processor.py:157} INFO - Started process (PID=2258) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:39:13.214+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:39:13.215+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:39:13.215+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:39:13.221+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:39:13.220+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:39:13.222+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:39:13.242+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.033 seconds
[2023-08-03T16:39:43.607+0000] {processor.py:157} INFO - Started process (PID=2287) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:39:43.609+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:39:43.611+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:39:43.610+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:39:43.617+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:39:43.616+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:39:43.619+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:39:43.639+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.036 seconds
[2023-08-03T16:40:14.053+0000] {processor.py:157} INFO - Started process (PID=2315) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:40:14.054+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:40:14.056+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:40:14.055+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:40:14.062+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:40:14.060+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:40:14.062+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:40:14.083+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.033 seconds
[2023-08-03T16:40:44.537+0000] {processor.py:157} INFO - Started process (PID=2343) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:40:44.538+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:40:44.539+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:40:44.539+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:40:44.548+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:40:44.543+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:40:44.549+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:40:44.578+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.044 seconds
[2023-08-03T16:41:15.097+0000] {processor.py:157} INFO - Started process (PID=2363) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:41:15.099+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:41:15.100+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:41:15.100+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:41:15.107+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:41:15.105+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:41:15.108+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:41:15.130+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.037 seconds
[2023-08-03T16:41:45.554+0000] {processor.py:157} INFO - Started process (PID=2393) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:41:45.555+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:41:45.557+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:41:45.557+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:41:45.563+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:41:45.561+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:41:45.564+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:41:45.584+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.036 seconds
[2023-08-03T16:42:16.043+0000] {processor.py:157} INFO - Started process (PID=2422) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:42:16.044+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:42:16.045+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:42:16.045+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:42:16.050+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:42:16.049+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:42:16.050+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:42:16.067+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.026 seconds
[2023-08-03T16:42:46.413+0000] {processor.py:157} INFO - Started process (PID=2442) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:42:46.415+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:42:46.416+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:42:46.416+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:42:46.423+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:42:46.421+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:42:46.424+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:42:46.445+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.036 seconds
[2023-08-03T16:43:16.809+0000] {processor.py:157} INFO - Started process (PID=2471) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:43:16.810+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:43:16.812+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:43:16.811+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:43:16.818+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:43:16.817+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:43:16.819+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:43:16.838+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.032 seconds
[2023-08-03T16:43:47.153+0000] {processor.py:157} INFO - Started process (PID=2499) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:43:47.155+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:43:47.156+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:43:47.156+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:43:47.163+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:43:47.161+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:43:47.164+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:43:47.187+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.039 seconds
[2023-08-03T16:44:17.621+0000] {processor.py:157} INFO - Started process (PID=2520) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:44:17.623+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T16:44:17.624+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:44:17.623+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:44:17.645+0000] {logging_mixin.py:150} INFO - [2023-08-03T16:44:17.632+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T16:44:17.652+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T16:44:17.687+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.069 seconds
[2023-08-03T17:50:00.988+0000] {processor.py:157} INFO - Started process (PID=2531) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T17:50:00.994+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T17:50:01.000+0000] {logging_mixin.py:150} INFO - [2023-08-03T17:50:00.999+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T17:50:01.031+0000] {logging_mixin.py:150} INFO - [2023-08-03T17:50:01.014+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T17:50:01.033+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T17:50:01.129+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.154 seconds
[2023-08-03T18:55:28.247+0000] {processor.py:157} INFO - Started process (PID=2560) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T18:55:28.249+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T18:55:28.254+0000] {logging_mixin.py:150} INFO - [2023-08-03T18:55:28.253+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T18:55:28.278+0000] {logging_mixin.py:150} INFO - [2023-08-03T18:55:28.267+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T18:55:28.279+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T18:55:28.339+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.107 seconds
[2023-08-03T20:21:11.465+0000] {processor.py:157} INFO - Started process (PID=2580) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T20:21:11.469+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T20:21:11.473+0000] {logging_mixin.py:150} INFO - [2023-08-03T20:21:11.472+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T20:21:11.493+0000] {logging_mixin.py:150} INFO - [2023-08-03T20:21:11.483+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T20:21:11.496+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T20:21:11.598+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.144 seconds
[2023-08-03T21:44:10.969+0000] {processor.py:157} INFO - Started process (PID=2610) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T21:44:10.972+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T21:44:10.977+0000] {logging_mixin.py:150} INFO - [2023-08-03T21:44:10.974+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T21:44:11.018+0000] {logging_mixin.py:150} INFO - [2023-08-03T21:44:11.009+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T21:44:11.019+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T21:44:11.150+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.195 seconds
[2023-08-03T23:04:48.867+0000] {processor.py:157} INFO - Started process (PID=2630) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T23:04:48.871+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T23:04:48.875+0000] {logging_mixin.py:150} INFO - [2023-08-03T23:04:48.873+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T23:04:48.904+0000] {logging_mixin.py:150} INFO - [2023-08-03T23:04:48.899+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T23:04:48.907+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T23:04:48.986+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.132 seconds
[2023-08-03T23:44:36.819+0000] {processor.py:157} INFO - Started process (PID=2659) to work on /opt/airflow/dags/template/adx-auction.py
[2023-08-03T23:44:36.834+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/adx-auction.py for tasks to queue
[2023-08-03T23:44:36.848+0000] {logging_mixin.py:150} INFO - [2023-08-03T23:44:36.847+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T23:44:36.915+0000] {logging_mixin.py:150} INFO - [2023-08-03T23:44:36.896+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/adx-auction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/adx-auction.py", line 12, in <module>
    dag_id=dag_id_to_replace,
NameError: name 'dag_id_to_replace' is not defined
[2023-08-03T23:44:36.917+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/adx-auction.py
[2023-08-03T23:44:37.268+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/adx-auction.py took 0.470 seconds
